# launcher name & url
launcher_name=Cubiq
launcher_app_name=Cubiq
launcher_short_name=Cubiq
url_home=https://github.com/CubiqLauncher/Cubiq

# your OAuth client id
#oauth_client_id=xxx

# your CurseForge API key
curseforge_api_key=$2a$10$1Z91gpCfwa3tIK9G3Y1q6.3t4T08e16CxmvmX8aEyNp0mqHe3tTyO

# default key, please add it yourself.
default_store_password=vh#nn%N(#eNjwfA78-77s6&f-cdd(@-7eana-e%!nhj%))!@c
default_key_password=sfv72ghSSNQaadf99-Q69!2

# launcher version
launcher_version_code=200043
launcher_version_name=2.6.1